### ISSUE TITLE
Mod is crashing

### ISSUE THREAD

**Issue by cyber5** [TazTxUK/MusicModCallback#15]
Looks like a recent commit is causing the game to crash. We should revert before we try to figure out what the problem is (I glanced through and couldn't find the problem).

**Comment by TazTxUK** [comment]
workshop version reverted to 6041dc691e909e202bf23874e85abdd3b41957d2 for now
The crash doesn't happen for me at all, I'll look into it more later.

**Comment by cyber5** [comment]
Sweet, yeah like I said, I studied the code for a bit and couldn't find an issue

**Comment by cyber5** [comment]
I'm starting to be skeptical that the game crashing is our fault. But we'll see if anyone responds to my question on the workshop page.

**Comment by cyber5** [comment]
I'm back from vacation and have my computer. I tested each of the two newest commits with only this mod enabled, and then again with only this mod and Nato's Soundtrack Menu enabled. No issues. I suggest we push the code back out and request that people tell us exactly which mods they are using when their game crashes because as far as I can tell the code on its own is fine.

**Comment by TazTxUK** [comment]
Yeah that sounds like a good idea. I'll push the latest commit out again.
