### ISSUE TITLE
Ultra Greed nightmare intro music is not played

### ISSUE THREAD

**Issue by TazTxUK** [TazTxUK/MusicModCallback#20]

**Comment by cyber5** [comment]
Does this refer to the nightmare cutscene jingle, or the boss portrait jingle? If the latter, I thought I already fixed that, but I can check again.

**Comment by TazTxUK** [comment]
Not sure, it was mentioned by maleverus.
If you've already fixed it then I'll close it

**Comment by cyber5** [comment]
I just played Greed Mode with only this mod enabled, and both the nightmare and boss portrait jingles play correctly. Perhaps Maleverus's local mod code isn't up-to-date. The code might not update if it has been edited locally. This happened to me a couple times and so now I have a separate mod folder where I do my experimentation.
