### ISSUE TITLE
Handle Death Certificate music correctly

### ISSUE THREAD

**Issue by cyber5** [TazTxUK/MusicModCallback#30]
I am nowhere near unlocking this item so not even sure exactly what this entails

**Comment by cyber5** [comment]
After a little YouTube research, we need to play MUSIC_DARK_CLOSET in the Death Certificate area

**Comment by cyber5** [comment]
I found some interesting information about "dimensions" in the mod docs, where dimension 0 is normal, dimension 1 is mirror/mineshaft, and dimension 2 is death certificate area. That type of thing could be used here and to make the mirror/mineshaft code more robust. Unfortunately, I haven't found a function equivalent to GetCurrentDimension().

**Comment by TazTxUK** [comment]
I've got an issue open on the Repentance API Issue Tracker
https://github.com/Meowlala/RepentanceAPIIssueTracker/issues/182

**Comment by NAT0P0TAT0** [comment]
have gotten around it by checking for the backdrop type, also isn't dark closet supposed to play after sleeping in moms bed at HOME? (aka STAGE8 - STAGETYPE_WOTL) didn't notice it before

**Comment by TazTxUK** [comment]
fixed in 8bf3afe9f3fbcbdf0b515ca345bb2f8bf740dcfc

**Comment by NAT0P0TAT0** [comment]
checked it out, its weird, according to the music manager its still playing 'Home' but the music is exactly the same as 'Echoes reverse' aka dark_closet, even continues playing smoothly if I use death certificate while in the dark version of home

**Comment by cyber5** [comment]
See issue #26 for a description of what's going on here. Basically, after sleeping in Mom's bed it should play ISAACS_HOUSE with the layer enabled.
