### ISSUE TITLE
Data Loading should handle missing data

### ISSUE THREAD

**Issue by cyber5** [TazTxUK/MusicModCallback#37]
If a variable is missing from the save.dat file, but the file is otherwise well-formed, then the variable will not be loaded. This is okay for booleans like "inmirroredworld" or "railcomplete" because they are false by default, and nil evaluates to false in if-statements in Lua. But for "darkhome", "secretjingles", and "railbuttons" this is problematic.

**Comment by TazTxUK** [comment]
probably fixed in df28b54904c3f9b5c1ecaf11a05166f7c286c437, needs checking
