### ISSUE TITLE
Angel Statues in Super Secret Rooms

### ISSUE THREAD

**Issue by cyber5** [TazTxUK/MusicModCallback#38]
Currently, the code for playing boss music during angel statue fights doesn't account for at least one super secret room layout that has an angel statue. Haven't tested in vanilla that the boss music would for sure play but I would bet it's supposed to.

**Comment by TazTxUK** [comment]
partially fixed in a15d15fe5d2b957d8ed7115fbcf1ca6024921dbb but needs all cases to be accounted for
