### ISSUE TITLE
Challenge "DELETE THIS"

### ISSUE THREAD

**Issue by cyber5** [TazTxUK/MusicModCallback#44]
Challenge 45, "DELETE THIS", is supposed to play random music each floor. I don't know exact probabilities of each track playing for a floor, but I assume every main floor track plus MUSIC_NULL are included.

**Comment by TazTxUK** [comment]
Fixed in [branch:rewrite](/TazTxUK/MusicModCallback/tree/rewrite), not yet included in current version

**Comment by TazTxUK** [comment]
rewrite is now the main version, so this is fixed.
